version: '3'

services:
  web:
    build: .
    command: bash -c "gunicorn --bind 0.0.0.0:8000"
    container_name: daksha
    restart: always
    volumes:
      - /daksha/test-data:/daksha/test-data
    ports:
      - "8083:8000"
    environment:
      STORAGE_PATH: "/daksha/test-data"
      APACHE_URL: ""
      EMAIL_HOST_USER: ""
      POSTMARK_TOKEN: ""
      GIT_USER: ""
      GIT_PASS: ""
      REPO_NAME: ""
      BRANCH_NAME: ""
      REPO_ORG: ""
      REPO_USER: ""
      DJANGO_SECRET_KEY: ""
      ALLOWED_HOSTS: ""

  engine-apache:
    image: httpd:2.4-alpine
    container_name: engine-apache
    restart: always
    volumes:
      - /daksha/test-data:/usr/local/apache2/htdocs/
    ports:
      - "8485:80"
